import WebSocket from "ws";
import { IClientWebSocket } from "../../types";
import roomsDB from "../db/rooms";

// send for both players in the room, after they are connected to the room
export const createGame = (indexRoom: string, wss: WebSocket.Server) => {
  roomsDB[indexRoom].roomUsers.map((user: { name: string; index: string }) => {
    wss.clients.forEach((client: IClientWebSocket) => {
      if (
        client.readyState === WebSocket.OPEN &&
        client.playerName === user.name
      ) {
        client.send(
          JSON.stringify({
            type: "create_game",
            id: 0,
            data: JSON.stringify({
              idGame: crypto.randomUUID(),
              idPlayer: client.playerId, // generated by server id for player in the game session
            }),
          })
        );
      }
    });
  });
};
